// GlobalComponents for Volar
declare module "@vue/runtime-core" {
    export interface GlobalComponents {
        Affix: typeof import("../types/viewuiplus.components")["Affix"];
        Alert: typeof import("../types/viewuiplus.components")["Alert"];
        Avatar: typeof import("../types/viewuiplus.components")["Avatar"];
        AvatarList: typeof import("../types/viewuiplus.components")["AvatarList"];
        Anchor: typeof import("../types/viewuiplus.components")["Anchor"];
        AnchorLink: typeof import("../types/viewuiplus.components")["AnchorLink"];
        Auth: typeof import("../types/viewuiplus.components")["Auth"];
        AutoComplete: typeof import("../types/viewuiplus.components")["AutoComplete"];
        BackTop: typeof import("../types/viewuiplus.components")["BackTop"];
        Badge: typeof import("../types/viewuiplus.components")["Badge"];
        Breadcrumb: typeof import("../types/viewuiplus.components")["Breadcrumb"];
        BreadcrumbItem: typeof import("../types/viewuiplus.components")["BreadcrumbItem"];
        Button: typeof import("../types/viewuiplus.components")["Button"];
        ButtonGroup: typeof import("../types/viewuiplus.components")["ButtonGroup"];
        Calendar: typeof import("../types/viewuiplus.components")["Calendar"];
        Card: typeof import("../types/viewuiplus.components")["Card"];
        Cell: typeof import("../types/viewuiplus.components")["Cell"];
        CellGroup: typeof import("../types/viewuiplus.components")["CellGroup"];
        Carousel: typeof import("../types/viewuiplus.components")["Carousel"];
        CarouselItem: typeof import("../types/viewuiplus.components")["CarouselItem"];
        Cascader: typeof import("../types/viewuiplus.components")["Cascader"];
        Checkbox: typeof import("../types/viewuiplus.components")["Checkbox"];
        CheckboxGroup: typeof import("../types/viewuiplus.components")["CheckboxGroup"];
        Col: typeof import("../types/viewuiplus.components")["Col"];
        Collapse: typeof import("../types/viewuiplus.components")["Collapse"];
        ColorPicker: typeof import("../types/viewuiplus.components")["ColorPicker"];
        Circle: typeof import("../types/viewuiplus.components")["Circle"];
        City: typeof import("../types/viewuiplus.components")["City"];
        CountDown: typeof import("../types/viewuiplus.components")["CountDown"];
        CountUp: typeof import("../types/viewuiplus.components")["CountUp"];
        DatePicker: typeof import("../types/viewuiplus.components")["DatePicker"];
        Divider: typeof import("../types/viewuiplus.components")["Divider"];
        Drawer: typeof import("../types/viewuiplus.components")["Drawer"];
        Dropdown: typeof import("../types/viewuiplus.components")["Dropdown"];
        DropdownItem: typeof import("../types/viewuiplus.components")["DropdownItem"];
        DropdownMenu: typeof import("../types/viewuiplus.components")["DropdownMenu"];
        Ellipsis: typeof import("../types/viewuiplus.components")["Ellipsis"];
        Exception: typeof import("../types/viewuiplus.components")["Exception"];
        Footer: typeof import("../types/viewuiplus.components")["Footer"];
        FooterToolbar: typeof import("../types/viewuiplus.components")["FooterToolbar"];
        Form: typeof import("../types/viewuiplus.components")["Form"];
        FormItem: typeof import("../types/viewuiplus.components")["FormItem"];
        GlobalFooter: typeof import("../types/viewuiplus.components")["GlobalFooter"];
        Header: typeof import("../types/viewuiplus.components")["Header"];
        Icon: typeof import("../types/viewuiplus.components")["Icon"];
        Image: typeof import("../types/viewuiplus.components")["Image"];
        ImagePreview: typeof import("../types/viewuiplus.components")["ImagePreview"];
        Input: typeof import("../types/viewuiplus.components")["Input"];
        InputNumber: typeof import("../types/viewuiplus.components")["InputNumber"];
        Link: typeof import("../types/viewuiplus.components")["Link"];
        Menu: typeof import("../types/viewuiplus.components")["Menu"];
        MenuItem: typeof import("../types/viewuiplus.components")["MenuItem"];
        MenuGroup: typeof import("../types/viewuiplus.components")["MenuGroup"];
        Option: typeof import("../types/viewuiplus.components")["Option"];
        OptionGroup: typeof import("../types/viewuiplus.components")["OptionGroup"];
        PageHeader: typeof import("../types/viewuiplus.components")["PageHeader"];
        Poptip: typeof import("../types/viewuiplus.components")["Poptip"];
        Progress: typeof import("../types/viewuiplus.components")["Progress"];
        Panel: typeof import("../types/viewuiplus.components")["Panel"];
        Radio: typeof import("../types/viewuiplus.components")["Radio"];
        RadioGroup: typeof import("../types/viewuiplus.components")["RadioGroup"];
        Rate: typeof import("../types/viewuiplus.components")["Rate"];
        Row: typeof import("../types/viewuiplus.components")["Row"];
        Scroll: typeof import("../types/viewuiplus.components")["Scroll"];
        Select: typeof import("../types/viewuiplus.components")["Select"];
        Slider: typeof import("../types/viewuiplus.components")["Slider"];
        Step: typeof import("../types/viewuiplus.components")["Step"];
        Steps: typeof import("../types/viewuiplus.components")["Steps"];
        Submenu: typeof import("../types/viewuiplus.components")["Submenu"];
        Switch: typeof import("../types/viewuiplus.components")["Switch"];
        TabPane: typeof import("../types/viewuiplus.components")["TabPane"];
        Table: typeof import("../types/viewuiplus.components")["Table"];
        Tabs: typeof import("../types/viewuiplus.components")["Tabs"];
        Tag: typeof import("../types/viewuiplus.components")["Tag"];
        Text: typeof import("../types/viewuiplus.components")["Text"];
        TimePicker: typeof import("../types/viewuiplus.components")["TimePicker"];
        Timeline: typeof import("../types/viewuiplus.components")["Timeline"];
        TimelineItem: typeof import("../types/viewuiplus.components")["TimelineItem"];
        Tooltip: typeof import("../types/viewuiplus.components")["Tooltip"];
        Transfer: typeof import("../types/viewuiplus.components")["Transfer"];
        Tree: typeof import("../types/viewuiplus.components")["Tree"];
        TreeSelect: typeof import("../types/viewuiplus.components")["TreeSelect"];
        Upload: typeof import("../types/viewuiplus.components")["Upload"];
        Space: typeof import("../types/viewuiplus.components")["Space"];
        Skeleton: typeof import("../types/viewuiplus.components")["Skeleton"];
        SkeletonItem: typeof import("../types/viewuiplus.components")["SkeletonItem"];
        Description: typeof import("../types/viewuiplus.components")["Description"];
        DescriptionList: typeof import("../types/viewuiplus.components")["DescriptionList"];
        Result: typeof import("../types/viewuiplus.components")["Result"];
        Layout: typeof import("../types/viewuiplus.components")["Layout"];
        Sider: typeof import("../types/viewuiplus.components")["Sider"];
        Content: typeof import("../types/viewuiplus.components")["Content"];
        Spin: typeof import("../types/viewuiplus.components")["Spin"];
    }
    interface ComponentCustomProperties {
        $Message: typeof import("../types/viewuiplus.components")["Message"];
        $notify: typeof import("../types/viewuiplus.components")["Notification"];
        $Modal: typeof import("../types/viewuiplus.components")["Modal"];
        $ImagePreview: typeof import("../types/viewuiplus.components")["ImagePreview"];
        $Copy: any;
        $ScrollIntoView: any;
        $ScrollTop: any;
        $Date: typeof import("dayjs");
    }
}

export {};
